# Generated by Django 6.0.5 on 2026-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0007_trainermonthlybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
