# Generated by Django 6.0.5 on 2026-05-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0008_gymclass_price_trainer_session_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Thời hạn gói (ngày)')),
                ('total_sessions', models.PositiveIntegerField(help_text='Tổng số buổi tập')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPTPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sessions', models.PositiveIntegerField()),
                ('used_sessions', models.PositiveIntegerField(default=0)),
                ('remaining_sessions', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('selected_weekdays', models.CharField(help_text="Danh sách thứ tự chọn (ví dụ: '0,2,4')", max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='gym_booking_backend.ptpackage')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_pt_packages', to='gym_booking_backend.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pt_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Thứ trong tuần (0=Monday)')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_schedules', to='gym_booking_backend.trainer')),
            ],
            options={
                'ordering': ['trainer', 'weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'weekday', 'start_time'), name='unique_trainer_weekday_start_time')],
            },
        ),
        migrations.CreateModel(
            name='PTBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(max_length=30, unique=True)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_trainer_bookings', to='gym_booking_backend.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_bookings', to=settings.AUTH_USER_MODEL)),
                ('user_pt_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='gym_booking_backend.userptpackage')),
            ],
            options={
                'ordering': ['booking_date', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('trainer', 'booking_date', 'start_time'), name='unique_trainer_pt_booking_slot'), models.UniqueConstraint(condition=models.Q(('status__in', ['confirmed', 'pending'])), fields=('user', 'booking_date', 'start_time'), name='unique_user_pt_booking_slot')],
            },
        ),
    ]
