# Generated by Django 6.0.5 on 2026-06-21 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gym_booking_backend', '0009_ptpackage_userptpackage_trainerschedule_ptbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='trainerbooking',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='trainermonthlybooking',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trainerbooking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='trainermonthlybooking',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='userptpackage',
            name='remaining_sessions',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='membershippackage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippackage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ptpackage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptpackage',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trainer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ptbooking',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pt_trainer_bookings', to='gym_booking_backend.trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerbooking',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal_bookings', to='gym_booking_backend.trainer'),
        ),
        migrations.AlterField(
            model_name='trainermonthlybooking',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_bookings', to='gym_booking_backend.trainer'),
        ),
        migrations.AlterField(
            model_name='userptpackage',
            name='selected_weekdays',
            field=models.JSONField(default=list, help_text='Danh sách thứ tự chọn, ví dụ: [0, 2, 4]'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='idx_booking_user_status'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['start_time', 'status'], name='idx_schedule_start_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_invoice_item_ct_oid'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='ptbooking',
            index=models.Index(fields=['booking_date'], name='idx_pt_booking_date'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['trainer'], name='idx_review_trainer'),
        ),
        migrations.AddIndex(
            model_name='trainerbooking',
            index=models.Index(fields=['trainer', 'status'], name='idx_tb_trainer_status'),
        ),
        migrations.AddIndex(
            model_name='trainerbooking',
            index=models.Index(fields=['start_time'], name='idx_tb_start_time'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'status'], name='idx_membership_user_status'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='check_schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.CheckConstraint(condition=models.Q(('current_participants__lte', models.F('max_participants'))), name='check_participants_not_exceeding'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('object_id__isnull', False)), fields=('content_type', 'object_id'), name='unique_invoice_item_per_object'),
        ),
        migrations.AddConstraint(
            model_name='membershipfreeze',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='check_freeze_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='check_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('trainer__isnull', False), ('gym_class__isnull', False), _connector='OR'), name='review_must_have_target'),
        ),
        migrations.AddConstraint(
            model_name='trainerbooking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='check_trainer_booking_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='trainermonthlybooking',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='check_monthly_booking_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='userptpackage',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='check_pt_package_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='userptpackage',
            constraint=models.CheckConstraint(condition=models.Q(('used_sessions__lte', models.F('total_sessions'))), name='check_used_not_exceeding_total'),
        ),
    ]
