# Generated by Django 6.0.5 on 2026-06-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0011_alter_trainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
