# Generated by Django 6.0.5 on 2026-06-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0012_profile_two_factor_enabled_profile_two_factor_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='Ví dụ: smtp.gmail.com', max_length=255, verbose_name='SMTP Host')),
                ('email_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_host_user', models.CharField(help_text='Địa chỉ email dùng để gửi thư', max_length=255, verbose_name='Tài khoản Email')),
                ('email_host_password', models.CharField(help_text='Mật khẩu hoặc mật khẩu ứng dụng SMTP (App Password)', max_length=255, verbose_name='Mật khẩu ứng dụng')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Sử dụng TLS')),
                ('is_active', models.BooleanField(default=False, help_text='Chỉ có duy nhất một cấu hình được kích hoạt tại một thời điểm', verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình Email SMTP',
                'verbose_name_plural': 'Cấu hình Email SMTP',
            },
        ),
    ]
