# Generated by Django 6.0.5 on 2026-06-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0013_emailsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userptpackage',
            name='package',
        ),
        migrations.RemoveConstraint(
            model_name='trainermonthlybooking',
            name='unique_active_trainer_monthly_booking',
        ),
        migrations.RemoveConstraint(
            model_name='trainermonthlybooking',
            name='check_monthly_booking_start_before_end',
        ),
        migrations.DeleteModel(
            name='PTPackage',
        ),
        migrations.DeleteModel(
            name='TrainerMonthlyBooking',
        ),
    ]
