# Generated by Django 6.0.5 on 2026-06-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking_backend', '0013_emailsetting'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_booking_status',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='idx_booking_user_status',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_active_booking',
        ),
        migrations.RemoveField(
            model_name='gymclass',
            name='category',
        ),
        migrations.RemoveField(
            model_name='membershippackage',
            name='allowed_categories',
        ),
        migrations.RemoveIndex(
            model_name='classschedule',
            name='idx_schedule_start_status',
        ),
        migrations.RemoveConstraint(
            model_name='classschedule',
            name='check_schedule_start_before_end',
        ),
        migrations.RemoveConstraint(
            model_name='classschedule',
            name='check_participants_not_exceeding',
        ),
        migrations.RemoveField(
            model_name='gymclass',
            name='trainer',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='review_must_have_target',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='review',
            name='gym_class',
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='GymClass',
        ),
    ]
